# Generated by Django 5.1.6 on 2025-02-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SibTransUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="choice",
            name="question",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="choice_text",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="votes",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
