# Generated by Django 5.1.7 on 2025-03-17 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_container_notification_rental_sibtranslog_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.user",
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="sibtranslog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="polls.user",
                verbose_name="Пользователь",
            ),
        ),
    ]
